Update F-OH-DATA
eclipse-oniro4openharmony/f-oh-data pull request #1
Opened 2024-11-21 14:25 UTC by imansmallapple

1. Translated Chinese Readme file into English
2. Added app deploy to oniro appStore procedure via docker
3. Added math punching app's icon and hap file
4. Added Dockerfile where the deploy procedure used

2024-11-21 17:47 UTC, frankplus requested changes
- can you update `allAppList.json` adding the math punching app
- please separate the commits: one commit for readme translation, one for hap and app list update, one for docker instruction addition to readme. Also with proper commit descrition

2024-11-21 17:47 UTC, frankplus commented on README.md
> +problem solved
these instructions are not relevant for this readme. These are enough.

````suggestion
## Start the server with Docker
### **Build the Docker Image**
Run the following command:

```bash
docker build -t f-oh-data .
```

### **Run the Docker Container**
To start the container:

```bash
docker run -d -p 5000:5000 f-oh-data
```
````

2024-11-22 07:54 UTC, imansmallapple commented
Commit seperated

2024-11-22 09:23 UTC, frankplus requested changes

2024-11-22 09:23 UTC, frankplus commented on README.md
> +problem solved
These changes should not be in the README translation commit

2024-11-22 09:23 UTC, frankplus commented on README.md
> -problem solved
after removing it from the "README translation" commit, these part should go away

2024-11-22 10:13 UTC, imansmallapple commented on README.md
> -problem solved
This part was removed from git history now

2024-11-22 10:21 UTC, frankplus commented
The commit author should be `chensong64@h-partners.com` for all the commits:

```
commit fcfe8895a012d476348b6b19e24c72218d4923dd (HEAD -> oniro, origin/oniro, origin/HEAD)
Author: chen <alf138540fun@gmail.com>
Date:   Thu Nov 21 20:21:04 2024 +0100

    Docker instruction addition to readme
    
    Signed-off-by: Chen <chensong64@h-partners.com>

commit 519f3349f0e6213bb86045c6f6aacbf85633d03e
Author: chen <alf138540fun@gmail.com>
Date:   Thu Nov 21 20:17:25 2024 +0100

    Add hap file and app list update
    
    Signed-off-by: Chen <chensong64@h-partners.com>

commit 735f5799ed519136262add03037d49624a49ccd2
Author: chen <alf138540fun@gmail.com>
Date:   Thu Nov 21 20:16:15 2024 +0100

    add Dockerfile
    
    Signed-off-by: Chen <chensong64@h-partners.com>

commit 9cac3293a85a02ec23dfca47943992e29165bb8d
Author: Chen <chensong64@h-partners.com>
Date:   Fri Nov 22 11:10:50 2024 +0100

    README translation
    
    Signed-off-by: Chen <chensong64@h-partners.com>
```

2024-11-22 10:50 UTC, imansmallapple commented
> The commit author should be `chensong64@h-partners.com` for all the commits:
> 
> ```
> commit fcfe8895a012d476348b6b19e24c72218d4923dd (HEAD -> oniro, origin/oniro, origin/HEAD)
> Author: chen <alf138540fun@gmail.com>
> Date:   Thu Nov 21 20:21:04 2024 +0100
> 
>     Docker instruction addition to readme
>     
>     Signed-off-by: Chen <chensong64@h-partners.com>
> 
> commit 519f3349f0e6213bb86045c6f6aacbf85633d03e
> Author: chen <alf138540fun@gmail.com>
> Date:   Thu Nov 21 20:17:25 2024 +0100
> 
>     Add hap file and app list update
>     
>     Signed-off-by: Chen <chensong64@h-partners.com>
> 
> commit 735f5799ed519136262add03037d49624a49ccd2
> Author: chen <alf138540fun@gmail.com>
> Date:   Thu Nov 21 20:16:15 2024 +0100
> 
>     add Dockerfile
>     
>     Signed-off-by: Chen <chensong64@h-partners.com>
> 
> commit 9cac3293a85a02ec23dfca47943992e29165bb8d
> Author: Chen <chensong64@h-partners.com>
> Date:   Fri Nov 22 11:10:50 2024 +0100
> 
>     README translation
>     
>     Signed-off-by: Chen <chensong64@h-partners.com>
> ```

The author was changed back now.

2024-11-22 10:54 UTC, merged